// <auto-generated />
using Excuses.Persistence.EFCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Excuses.Persistence.EFCore.Migrations
{
    [DbContext(typeof(ExcusesDbContext))]
    partial class ExcusesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Excuses.Persistence.Shared.Models.Excuse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "category");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "text");

                    b.HasKey("Id");

                    b.ToTable("Excuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "work",
                            Text = "My computer exploded"
                        },
                        new
                        {
                            Id = 2,
                            Category = "pets",
                            Text = "My cat hid my car keys"
                        },
                        new
                        {
                            Id = 3,
                            Category = "general",
                            Text = "Gravity stopped working for me temporarily"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
